[versions]
xtraplatform-build = "4.7.2"
spotless = "6.15.0"
node = "3.5.1"

[plugins]
xtraplatform-application = { id = "de.interactive_instruments.xtraplatform-application", version.ref = "xtraplatform.build" }
xtraplatform-layer = { id = "de.interactive_instruments.xtraplatform-layer", version.ref = "xtraplatform.build" }
xtraplatform-composite = { id = "de.interactive_instruments.xtraplatform-composite", version.ref = "xtraplatform.build" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
node = { id = "com.github.node-gradle.node", version.ref = "node" }

